[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
moonbase = "9xwvYvnjA3TVRpPVUonvDQcchTxgo7dRi7zwi2zvoSAG"
raydium_cp_swap = "DFbiecJY7wg2y6H2VVdQV8nEGPZdd5FFvN5MjNMdi4a1"

[programs.devnet]
moonbase = "C8KGBzyXUpoahNKaNtT1oCTeinGEsuECX7xrhjdKvHBz"
mpl-core = "AKDm1gXxpnJE23aYTtmNE8E9CagM7gkvjKGegDZ9qTPD"
raydium_cp_swap = "6VhZfCR6DRTfFSbLZZpd8vSCadfYgQteKkQodA4X5mdz"

[provider]
cluster = "localnet"
wallet = "~/Desktop/LifeOrDream Labs/DogeBTC/MineBtc-fi/wallet-keypair.json"

[workspace]
members = ["programs/*"]


[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false
