[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
minebtc = "EkLZDQo3vKytwoDj1PHcLPti13SZULZr8KsRkpu28zpd"
degenbtc_market = "MarKEt1111111111111111111111111111111111111"
raydium_cp_swap = "DFbiecJY7wg2y6H2VVdQV8nEGPZdd5FFvN5MjNMdi4a1"

[programs.devnet]
minebtc = "FoACK8AbSqy9rPtRccTyqxhgHX9xSLWYnBEfXvDNPX61"
degenbtc_market = "Dh4LLRQHqmBeYHYXs3haYTsXTkBa11APJqq6korkc4hg"
mpl-core = "AKDm1gXxpnJE23aYTtmNE8E9CagM7gkvjKGegDZ9qTPD"
raydium_cp_swap = "68NJDT912wd5EuCB3jDabR77gCjM3xgfkJ21hUxgfYJ4"

[provider]
cluster = "devnet"
wallet = "./devnet-wallet-keypair.json"

[workspace]
members = ["programs/*"]


[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[programs.mainnet]
minebtc = "1eotiTH2UxCpPMmtzUDGqf1b8dwM7AMKb8a2Tio51an"
degenbtc_market = "BCuofnvb7QUP6xLH83EEbKFNjxz5T5Jp4xLqfEdURYRg"
raydium_cp_swap = "CPMMoo8L3F4NbTegBCKVNunggL7H1ZpdTHKxQB5qKP1C"