#!/usr/bin/env node
//
// sync_deployment_to_repos.js
// ---------------------------
// One-click sync from MineBtc-fi deployment artifacts to:
//   - MineBtcBackend   (sister folder)
//   - mdogeWifBtcFE    (sister folder)
//
// Reads setup_scripts/deployments/website.json (generated by website_config.js)
// and:
//   1. Copies fresh IDLs from target/idl/ → both repos
//   2. Writes MineBtcBackend/deployment.json (under the active cluster key)
//   3. Patches mdogeWifBtcFE/hooks/config.ts cluster block (devnet OR mainnet)
//
// Cluster resolution priority:
//   --cluster=<name> CLI arg  →  config.json network.cluster  →  first key in website.json
//
// Usage:
//   cd MineBtc-fi/setup_scripts && node sync_deployment_to_repos.js
//   cd MineBtc-fi/setup_scripts && node sync_deployment_to_repos.js --cluster=mainnet
//   cd MineBtc-fi/setup_scripts && node sync_deployment_to_repos.js --dry-run
//

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const DRY_RUN = process.argv.includes("--dry-run");

// Optional --cluster=<name> or --cluster <name> override
const clusterArg = (() => {
  for (let i = 2; i < process.argv.length; i++) {
    const a = process.argv[i];
    if (a.startsWith("--cluster=")) return a.slice("--cluster=".length).trim();
    if (a === "--cluster" && process.argv[i + 1]) return process.argv[i + 1].trim();
  }
  return null;
})();

// ───────── Paths ─────────
const REPO_ROOT = path.resolve(__dirname, "..");
const BACKEND_REPO = path.resolve(REPO_ROOT, "..", "MineBtcBackend");
const FRONTEND_REPO = path.resolve(REPO_ROOT, "..", "mdogeWifBtcFE");

const WEBSITE_JSON_PATH = path.join(
  REPO_ROOT,
  "setup_scripts",
  "deployments",
  "website.json",
);
const CONFIG_JSON_PATH = path.join(REPO_ROOT, "setup_scripts", "config.json");
const IDL_SOURCE_DIR = path.join(REPO_ROOT, "target", "idl");

const BACKEND_IDL_DIR = path.join(BACKEND_REPO, "idl");
const BACKEND_DEPLOYMENT_PATH = path.join(BACKEND_REPO, "deployment.json");

const FRONTEND_IDL_DIR = path.join(FRONTEND_REPO, "idl");
const FRONTEND_CONFIG_PATH = path.join(FRONTEND_REPO, "hooks", "config.ts");

// ───────── Validate repos exist ─────────
function assertDir(p, name) {
  if (!fs.existsSync(p)) {
    console.error(`❌ ${name} not found at: ${p}`);
    console.error(
      `   Expected sister folder layout: MineBtc-fi/  MineBtcBackend/  mdogeWifBtcFE/`,
    );
    process.exit(1);
  }
}
assertDir(BACKEND_REPO, "MineBtcBackend");
assertDir(FRONTEND_REPO, "mdogeWifBtcFE");
assertDir(IDL_SOURCE_DIR, "IDL source dir (target/idl)");

// ───────── Load website.json ─────────
let website;
try {
  website = JSON.parse(fs.readFileSync(WEBSITE_JSON_PATH, "utf-8"));
} catch (e) {
  console.error(`❌ Failed to read ${WEBSITE_JSON_PATH}: ${e.message}`);
  console.error(
    `   Run: node website_config.js  (to generate website.json first)`,
  );
  process.exit(1);
}

// Resolve cluster:
//   1. --cluster=<name> CLI arg
//   2. config.json network.cluster
//   3. first non-pda_seeds key in website.json
const availableClusters = Object.keys(website).filter((k) => k !== "pda_seeds");
let cluster = clusterArg;
if (!cluster) {
  try {
    const cfg = JSON.parse(fs.readFileSync(CONFIG_JSON_PATH, "utf-8"));
    if (cfg?.network?.cluster) cluster = cfg.network.cluster;
  } catch {
    /* config.json optional */
  }
}
if (!cluster) cluster = availableClusters[0] || "devnet";

const w = website[cluster];
if (!w) {
  console.error(
    `❌ Cluster "${cluster}" not found in website.json. Available: ${availableClusters.join(", ") || "(none)"}`,
  );
  process.exit(1);
}

console.log(`🔄 Syncing deployment for cluster: ${cluster}`);

// ═════════════════════════════════════════════════════════════════════════════
// 1. COPY IDLs
// ═════════════════════════════════════════════════════════════════════════════
const IDL_FILES = [
  "minebtc.json",
  "degenbtc_market.json",
  "raydium_cp_swap.json",
];

function copyIdls() {
  for (const file of IDL_FILES) {
    const src = path.join(IDL_SOURCE_DIR, file);
    if (!fs.existsSync(src)) {
      console.warn(`⚠️  Skipping missing IDL: ${file}`);
      continue;
    }
    for (const destDir of [BACKEND_IDL_DIR, FRONTEND_IDL_DIR]) {
      if (!fs.existsSync(destDir)) fs.mkdirSync(destDir, { recursive: true });
      const dest = path.join(destDir, file);
      if (DRY_RUN) {
        console.log(
          `[DRY] Would copy IDL ${file} → ${path.relative(process.cwd(), dest)}`,
        );
      } else {
        fs.copyFileSync(src, dest);
        console.log(
          `✅ Copied IDL ${file} → ${path.relative(process.cwd(), dest)}`,
        );
      }
    }
  }
}

// ═════════════════════════════════════════════════════════════════════════════
// 2. BUILD BACKEND deployment.json
// ═════════════════════════════════════════════════════════════════════════════

function buildBackendDeployment() {
  const now = new Date().toISOString();

  // Start from existing backend deployment if available (preserves fields
  // website.json doesn't know about, e.g. marketplace_fee_bps)
  let existing = {};
  if (fs.existsSync(BACKEND_DEPLOYMENT_PATH)) {
    try {
      existing = JSON.parse(fs.readFileSync(BACKEND_DEPLOYMENT_PATH, "utf-8"));
    } catch {}
  }
  const base = existing[cluster] || {};

  // Helper to safely read nested website values
  const v = (pathStr, fallback) => {
    const parts = pathStr.split(".");
    let cur = w;
    for (const p of parts) {
      if (cur == null) return fallback;
      cur = cur[p];
    }
    return cur !== undefined ? cur : fallback;
  };

  // Build faction_states array from website factions
  const factionStates = (w.factions || []).map((f) => ({
    faction_id: f.faction_id,
    name: f.name || f.faction_name,
    faction_state_pda: f.state_pda,
  }));

  // Build lootbox_queues map
  const lootboxQueues = {};
  if (w.lootbox_queues) {
    for (const entry of w.lootbox_queues) {
      const name = entry.faction_name || entry.name;
      if (name) lootboxQueues[name] = entry.queue_pda;
    }
  }

  // Build fee_config with "new" prefix (matches contract admin ix shape)
  const sfc = w.sol_fee_config || {};
  const feeConfig = {
    newProtocolFeePct:
      sfc.protocol_fee_pct ?? base.fee_config?.newProtocolFeePct ?? 15,
    newBuybackPct: sfc.buyback_pct ?? base.fee_config?.newBuybackPct ?? 70,
    newStakersPct: sfc.stakers_pct ?? base.fee_config?.newStakersPct ?? 10,
    newMinebtcStakersPct:
      sfc.minebtc_stakers_pct ?? base.fee_config?.newMinebtcStakersPct ?? 3,
    newMinebtcWinnersPct:
      sfc.minebtc_winners_pct ?? base.fee_config?.newMinebtcWinnersPct ?? 50,
    newMinebtcSameFactionPct:
      sfc.minebtc_same_faction_pct ??
      base.fee_config?.newMinebtcSameFactionPct ??
      21,
    newMinebtcJackpotPct:
      sfc.minebtc_jackpot_pct ?? base.fee_config?.newMinebtcJackpotPct ?? 5,
    newHodlTaxPct: sfc.hodl_tax_pct ?? base.fee_config?.newHodlTaxPct ?? 10,
    snapshotInterval:
      sfc.snapshot_interval ?? base.fee_config?.snapshotInterval ?? 300,
    newCycleSolSplitPct:
      sfc.cycle_sol_split_pct ?? base.fee_config?.newCycleSolSplitPct ?? 5,
    newNftMarketMakingPct:
      sfc.nft_market_making_pct ?? base.fee_config?.newNftMarketMakingPct ?? 3,
  };

  const out = {
    [cluster]: {
      // Programs
      MINE_BTC_PROGRAM_ID: v("programs.minebtc", base.MINE_BTC_PROGRAM_ID),
      DEGENBTC_MARKET_PROGRAM_ID: v(
        "programs.market",
        base.DEGENBTC_MARKET_PROGRAM_ID,
      ),
      RAYDIUM_CP_PROGRAM_ID: v(
        "programs.raydium_cp_swap",
        base.RAYDIUM_CP_PROGRAM_ID,
      ),

      // Network
      rpc_url: v("network.rpc_url", base.rpc_url),
      commitment: v("network.commitment", base.commitment),

      // dBTC token
      dbtc_mintAddress: v("dbtc.mint", base.dbtc_mintAddress),
      dbtc_mintAuthority: base.dbtc_mintAuthority ?? null,
      dbtc_burnTaxBps: v("dbtc.transfer_fee_bps", base.dbtc_burnTaxBps),
      dbtc_maxBurnAmount: v(
        "dbtc.max_transfer_fee_lamports",
        base.dbtc_maxBurnAmount,
      ),
      dbtc_decimals: v("dbtc.decimals", base.dbtc_decimals),

      // Raydium pool
      raydium_pool_state: v("raydium_pool.pool_state", base.raydium_pool_state),
      raydium_lp_mint: v("raydium_pool.lp_mint", base.raydium_lp_mint),
      raydium_token0_vault: v(
        "raydium_pool.token_0_vault",
        base.raydium_token0_vault,
      ),
      raydium_token1_vault: v(
        "raydium_pool.token_1_vault",
        base.raydium_token1_vault,
      ),
      raydium_authority: v(
        "raydium_pool.pool_authority",
        base.raydium_authority,
      ),
      raydium_observation_state: v(
        "raydium_pool.observation_state",
        base.raydium_observation_state,
      ),
      raydium_amm_config: v("raydium_pool.amm_config", base.raydium_amm_config),
      is_dbtc_token0: v("raydium_pool.is_dbtc_token_0", base.is_dbtc_token0),
      token0_mint: v("raydium_pool.token_0_mint", base.token0_mint),
      token1_mint: v("raydium_pool.token_1_mint", base.token1_mint),

      // MineBTC PDAs
      globalConfig_pda: v("minebtc.global_config", base.globalConfig_pda),
      mineBtcMining_pda: v("minebtc.dbtc_mining", base.mineBtcMining_pda),
      sol_treasury_pda: v("minebtc.sol_treasury", base.sol_treasury_pda),
      hashbeasts_treasury_pda: v(
        "minebtc.sol_treasury",
        base.hashbeasts_treasury_pda,
      ),
      unrefinedRewards_pda: v("minebtc.hodl_pool", base.unrefinedRewards_pda),
      hodlPool_pda: v("minebtc.hodl_pool", base.hodlPool_pda),
      autominerCustody_pda: v(
        "minebtc.autominer_custody",
        base.autominerCustody_pda,
      ),

      // Mining vault
      dbtc_token_vault: v("mining_vault.vault", base.dbtc_token_vault),
      minebtc_vault_authority: v(
        "mining_vault.authority",
        base.minebtc_vault_authority,
      ),
      mining_start_timestamp: base.mining_start_timestamp ?? 1778457600,
      degen_btc_per_round: v(
        "mining_vault.per_round_emission_lamports",
        base.degen_btc_per_round,
      ),

      // Game
      hashpowerConfig_pda: v(
        "minebtc.hashpower_config",
        base.hashpowerConfig_pda,
      ),
      global_game_state_pda: v("game.global_state", base.global_game_state_pda),
      round_duration_seconds: v(
        "game.round_duration_seconds",
        base.round_duration_seconds,
      ),

      // Faction war
      faction_war_config_pda: v(
        "faction_war.config",
        base.faction_war_config_pda,
      ),
      starting_faction_war_id: v(
        "faction_war.starting_war_id",
        base.starting_faction_war_id,
      ),
      sol_rewards_vault: v(
        "faction_war.sol_rewards_vault",
        base.sol_rewards_vault,
      ),
      sol_prize_pot_vault: v(
        "faction_war.sol_prize_pot_vault",
        base.sol_prize_pot_vault,
      ),

      // HashBeasts
      hashbeast_collection: v(
        "hashbeasts.collection",
        base.hashbeast_collection,
      ),
      hashbeast_collection_authority: v(
        "hashbeasts.collection_authority",
        base.hashbeast_collection_authority,
      ),
      lp_token_account: v("lp_token.token_account", base.lp_token_account),
      lp_token_mint: v("lp_token.mint", base.lp_token_mint),

      // System
      referral_rewards_pda: v(
        "system.referral_rewards_sentinel",
        base.referral_rewards_pda,
      ),
      buybacks_account_pda: v(
        "system.buybacks_account",
        base.buybacks_account_pda,
      ),
      buybacks_sol_vault_pda: v(
        "system.buybacks_sol_vault",
        base.buybacks_sol_vault_pda,
      ),

      // Custodians
      minebtcCustodian_pda: v("custodians.dbtc", base.minebtcCustodian_pda),
      minebtcCustodian_authority: v(
        "custodians.dbtc_authority",
        base.minebtcCustodian_authority,
      ),
      liquidityCustodian_pda: v("custodians.lp", base.liquidityCustodian_pda),
      liquidityCustodian_authority: v(
        "custodians.lp_authority",
        base.liquidityCustodian_authority,
      ),

      // HashBeast config
      hashbeast_config_pda: v("hashbeasts.config", base.hashbeast_config_pda),
      hashbeast_base_price: v(
        "hashbeasts.base_price_lamports",
        base.hashbeast_base_price,
      ),
      hashbeast_curve_a: v("hashbeasts.curve_a", base.hashbeast_curve_a),
      hashbeast_max_supply: v(
        "hashbeasts.max_supply",
        base.hashbeast_max_supply,
      ),
      hashbeast_genesis_mint_limit: v(
        "hashbeasts.genesis_mint_limit",
        base.hashbeast_genesis_mint_limit,
      ),
      hashbeast_max_genesis_mints_per_faction: v(
        "hashbeasts.max_genesis_mints_per_faction",
        base.hashbeast_max_genesis_mints_per_faction,
      ),
      hashbeast_mint_config_pda: v(
        "hashbeasts.mint_config",
        base.hashbeast_mint_config_pda,
      ),

      // Tax
      tax_config_pda: v("tax.config", base.tax_config_pda),
      withdraw_withheld_authority: v(
        "tax.withdraw_withheld_authority",
        base.withdraw_withheld_authority,
      ),
      transfer_fee_config_authority: v(
        "tax.withdraw_withheld_authority",
        base.transfer_fee_config_authority,
      ),
      faction_treasury_vault: v(
        "tax.faction_treasury_vault",
        base.faction_treasury_vault,
      ),

      // Marketplace
      nft_sale_sol_vault: v(
        "marketplace.sale_sol_vault",
        base.nft_sale_sol_vault,
      ),
      marketplace_config_pda: v(
        "marketplace.config",
        base.marketplace_config_pda,
      ),
      inventory_pool_pda: v(
        "marketplace.inventory_pool",
        base.inventory_pool_pda,
      ),
      floor_queue_pda: v("marketplace.floor_queue", base.floor_queue_pda),
      sale_history_pda: v("marketplace.sale_history", base.sale_history_pda),
      floor_history_pda: v("marketplace.floor_history", base.floor_history_pda),
      inventory_sweep_vault_pda: v(
        "marketplace.inventory_sweep_vault",
        base.inventory_sweep_vault_pda,
      ),

      // Preserve marketplace admin/fee fields if they exist
      marketplace_admin: base.marketplace_admin ?? v("marketplace.admin", null),
      marketplace_fee_bps:
        base.marketplace_fee_bps ?? v("marketplace.fee_bps", null),
      marketplace_min_price_lamports:
        base.marketplace_min_price_lamports ??
        v("marketplace.min_price_lamports", null),
      fee_recipient: v(
        "authorities.fee_recipient_multisig",
        v("minebtc.fee_recipient", base.fee_recipient),
      ),
      marketplace_fee_recipient: v(
        "marketplace.fee_recipient",
        base.marketplace_fee_recipient,
      ),

      // Lootbox / factions
      lootbox_queues: Object.keys(lootboxQueues).length
        ? lootboxQueues
        : base.lootbox_queues,
      faction_war_sol_vault: v(
        "faction_war.sol_vault",
        base.faction_war_sol_vault,
      ),

      // Lists
      supported_factions: (w.factions || []).map(
        (f) => f.name || f.faction_name,
      ),
      faction_states: factionStates,
      ticket_tiers: (w.ticket_tiers || []).map((t) => ({
        tier_index: t.tier_index,
        ticket_value: Number(t.ticket_value_lamports || t.ticket_value),
      })),

      // Fee config
      fee_config: feeConfig,

      // Sync marker
      [`synced_from_minebtc_fi_${cluster}_at`]: now,
    },
  };

  // Preserve any other cluster blocks already present (so a devnet sync
  // doesn't clobber an existing mainnet entry and vice-versa).
  for (const k of Object.keys(existing)) {
    if (k !== cluster && !(k in out)) out[k] = existing[k];
  }

  return JSON.stringify(out, null, 2) + "\n";
}

function writeBackendDeployment() {
  const json = buildBackendDeployment();
  if (DRY_RUN) {
    console.log(
      `[DRY] Would write ${path.relative(process.cwd(), BACKEND_DEPLOYMENT_PATH)}`,
    );
    return;
  }
  fs.writeFileSync(BACKEND_DEPLOYMENT_PATH, json);
  console.log(`✅ Wrote backend deployment.json`);
}

// ═════════════════════════════════════════════════════════════════════════════
// 3. PATCH FRONTEND hooks/config.ts
// ═════════════════════════════════════════════════════════════════════════════

function generateFrontendDevnetBlock() {
  const v = (pathStr, fallback) => {
    const parts = pathStr.split(".");
    let cur = w;
    for (const p of parts) {
      if (cur == null) return fallback;
      cur = cur[p];
    }
    return cur !== undefined ? cur : fallback;
  };

  const fmtStr = (s) => JSON.stringify(s ?? "");
  const fmtNum = (n) => (n === undefined || n === null ? "null" : String(n));

  const factionStates = (w.factions || []).map((f) => ({
    faction_id: f.faction_id,
    name: f.name || f.faction_name,
    faction_state_pda: f.state_pda,
  }));

  const lootboxQueues = {};
  if (w.lootbox_queues) {
    for (const entry of w.lootbox_queues) {
      const name = entry.faction_name || entry.name;
      if (name) lootboxQueues[name] = entry.queue_pda;
    }
  }

  const sfc = w.sol_fee_config || {};

  // Note: some frontend fields use slightly different casing than backend.
  const lines = [
    `${cluster}: {`,
    `    // ─── Programs ───`,
    `    MINE_BTC_PROGRAM_ID: ${fmtStr(v("programs.minebtc"))},`,
    `    DEGENBTC_MARKET_PROGRAM_ID: ENV_DEGENBTC_MARKET_PROGRAM_ID || DEVNET_DEGENBTC_MARKET_PROGRAM_ID,`,
    `    degenbtc_market_program_id: ENV_DEGENBTC_MARKET_PROGRAM_ID || DEVNET_DEGENBTC_MARKET_PROGRAM_ID,`,
    `    RAYDIUM_CP_PROGRAM_ID: ${fmtStr(v("programs.raydium_cp_swap"))},`,
    `    rpc_url: getReadRpcEndpoint("${cluster}"),`,
    `    commitment: ${fmtStr(v("network.commitment"))},`,
    `    dbtc_mintAddress: ${fmtStr(v("dbtc.mint"))},`,
    `    dbtc_mintAuthority: null,`,
    `    dbtc_burnTaxBps: ${fmtNum(v("dbtc.transfer_fee_bps"))},`,
    `    dbtc_maxBurnAmount: ${fmtNum(v("dbtc.max_transfer_fee_lamports"))},`,
    `    dbtc_decimals: ${fmtNum(v("dbtc.decimals"))},`,
    `    raydium_pool_state: ${fmtStr(v("raydium_pool.pool_state"))},`,
    `    raydium_lp_mint: ${fmtStr(v("raydium_pool.lp_mint"))},`,
    `    raydium_token0_vault: ${fmtStr(v("raydium_pool.token_0_vault"))},`,
    `    raydium_token1_vault: ${fmtStr(v("raydium_pool.token_1_vault"))},`,
    `    raydium_authority: ${fmtStr(v("raydium_pool.pool_authority"))},`,
    `    raydium_observation_state: ${fmtStr(v("raydium_pool.observation_state"))},`,
    `    raydium_amm_config: ${fmtStr(v("raydium_pool.amm_config"))},`,
    `    is_dbtc_token0: ${v("raydium_pool.is_dbtc_token_0") ?? true},`,
    `    token0_mint: ${fmtStr(v("raydium_pool.token_0_mint"))},`,
    `    token1_mint: ${fmtStr(v("raydium_pool.token_1_mint"))},`,
    `    globalConfig_pda: ${fmtStr(v("minebtc.global_config"))},`,
    `    degenBtcMining_pda: ${fmtStr(v("minebtc.dbtc_mining"))},`,
    `    sol_treasury_pda: ${fmtStr(v("minebtc.sol_treasury"))},`,
    `    hashbeasts_treasury_pda: ${fmtStr(v("minebtc.sol_treasury"))},`,
    `    unrefinedRewards_pda: ${fmtStr(v("minebtc.hodl_pool"))},`,
    `    hodlPool_pda: ${fmtStr(v("minebtc.hodl_pool"))},`,
    `    autominerCustody_pda: ${fmtStr(v("minebtc.autominer_custody"))},`,
    `    dbtc_token_vault: ${fmtStr(v("mining_vault.vault"))},`,
    `    dbtc_vault_authority: ${fmtStr(v("mining_vault.authority"))},`,
    `    mining_start_timestamp: 1778457600,`,
    `    degen_btc_per_round: ${fmtStr(v("mining_vault.per_round_emission_lamports"))},`,
    `    hashpowerConfig_pda: ${fmtStr(v("minebtc.hashpower_config"))},`,
    `    global_game_state_pda: ${fmtStr(v("game.global_state"))},`,
    `    round_duration_seconds: ${fmtNum(v("game.round_duration_seconds"))},`,
    `    faction_war_config_pda: ${fmtStr(v("faction_war.config"))},`,
    `    starting_faction_war_id: ${fmtNum(v("faction_war.starting_war_id"))},`,
    `    sol_rewards_vault: ${fmtStr(v("faction_war.sol_rewards_vault"))},`,
    `    sol_prize_pot_vault: ${fmtStr(v("faction_war.sol_prize_pot_vault"))},`,
    `    hashbeast_collection: ${fmtStr(v("hashbeasts.collection"))},`,
    `    hashbeast_collection_authority: ${fmtStr(v("hashbeasts.collection_authority"))},`,
    `    lp_token_account: ${fmtStr(v("lp_token.token_account"))},`,
    `    lp_token_mint: ${fmtStr(v("lp_token.mint"))},`,
    `    referral_rewards_pda: ${fmtStr(v("system.referral_rewards_sentinel"))},`,
    `    buybacks_account_pda: ${fmtStr(v("system.buybacks_account"))},`,
    `    buybacks_sol_vault_pda: ${fmtStr(v("system.buybacks_sol_vault"))},`,
    `    minebtcCustodian_pda: ${fmtStr(v("custodians.dbtc"))},`,
    `    minebtcCustodian_authority: ${fmtStr(v("custodians.dbtc_authority"))},`,
    `    dbtcCustodian_pda: ${fmtStr(v("custodians.dbtc"))},`,
    `    dbtcCustodian_authority: ${fmtStr(v("custodians.dbtc_authority"))},`,
    `    liquidityCustodian_pda: ${fmtStr(v("custodians.lp"))},`,
    `    liquidityCustodian_authority: ${fmtStr(v("custodians.lp_authority"))},`,
    `    hashbeast_config_pda: ${fmtStr(v("hashbeasts.config"))},`,
    `    hashbeast_base_price: ${fmtStr(v("hashbeasts.base_price_lamports"))},`,
    `    hashbeast_curve_a: ${fmtStr(v("hashbeasts.curve_a"))},`,
    `    tax_config_pda: ${fmtStr(v("tax.config"))},`,
    `    withdraw_withheld_authority: ${fmtStr(v("tax.withdraw_withheld_authority"))},`,
    `    faction_treasury_vault: ${fmtStr(v("tax.faction_treasury_vault"))},`,
    `    nft_floor_sweep_vault: ${fmtStr(v("marketplace.inventory_sweep_vault"))},`,
    `    nft_sale_sol_vault: ${fmtStr(v("marketplace.inventory_sweep_vault"))},`,
    `    marketplace_config_pda: ${fmtStr(v("marketplace.config"))},`,
    `    inventory_pool_pda: ${fmtStr(v("marketplace.inventory_pool"))},`,
    `    floor_queue_pda: ${fmtStr(v("marketplace.floor_queue"))},`,
    `    sale_history_pda: ${fmtStr(v("marketplace.sale_history"))},`,
    `    floor_history_pda: ${fmtStr(v("marketplace.floor_history"))},`,
    `    inventory_sweep_vault_pda: ${fmtStr(v("marketplace.inventory_sweep_vault"))},`,
    `    lootbox_queue_pdas: ${JSON.stringify(lootboxQueues, null, 6).replace(/^\{/m, "{").replace(/\}$/m, "  }")},`,
    `    base_creation_cost: ${fmtNum(v("hashbeasts.base_price_lamports"))},`,
    `    loot_percentage: ${v("hashbeasts.loot_percentage") != null ? fmtNum(v("hashbeasts.loot_percentage")) : 10},`,
    `    ticket_tiers: ${JSON.stringify(
      (w.ticket_tiers || []).map((t) => ({
        tier_index: t.tier_index,
        ticket_value: Number(t.ticket_value_lamports || t.ticket_value),
      })),
      null,
      6,
    )},`,
    `    supported_factions: ${JSON.stringify(
      (w.factions || []).map((f) => f.name || f.faction_name),
      null,
      6,
    )},`,
    `    faction_states: ${JSON.stringify(factionStates, null, 6)},`,
    `    fee_recipient: ${fmtStr(v("authorities.fee_recipient_multisig", v("minebtc.fee_recipient")))},`,
    `    marketplace_fee_recipient: ${fmtStr(v("marketplace.fee_recipient"))},`,
    `    transfer_fee_config_authority: ${fmtStr(v("tax.withdraw_withheld_authority"))},`,
    `    faction_war_sol_vault: ${fmtStr(v("faction_war.sol_vault"))},`,
    `    hashbeast_mint_config_pda: ${fmtStr(v("hashbeasts.mint_config"))},`,
    `    synced_from_minebtc_fi_${cluster}_at: ${fmtStr(new Date().toISOString())},`,
    `    hashbeast_genesis_mint_limit: ${fmtStr(v("hashbeasts.genesis_mint_limit"))},`,
    `    hashbeast_max_genesis_mints_per_faction: ${fmtStr(v("hashbeasts.max_genesis_mints_per_faction"))},`,
    `    fee_config: {`,
    `      newProtocolFeePct: ${fmtNum(sfc.protocol_fee_pct) ?? 15},`,
    `      newBuybackPct: ${fmtNum(sfc.buyback_pct) ?? 70},`,
    `      newStakersPct: ${fmtNum(sfc.stakers_pct) ?? 10},`,
    `      newMinebtcStakersPct: ${fmtNum(sfc.minebtc_stakers_pct) ?? 3},`,
    `      newMinebtcWinnersPct: ${fmtNum(sfc.minebtc_winners_pct) ?? 50},`,
    `      newMinebtcSameFactionPct: ${fmtNum(sfc.minebtc_same_faction_pct) ?? 21},`,
    `      newMinebtcJackpotPct: ${fmtNum(sfc.minebtc_jackpot_pct) ?? 5},`,
    `      newHodlTaxPct: ${fmtNum(sfc.hodl_tax_pct) ?? 10},`,
    `      snapshotInterval: ${fmtNum(sfc.snapshot_interval) ?? 300},`,
    `      newCycleSolSplitPct: ${fmtNum(sfc.cycle_sol_split_pct) ?? 5},`,
    `      newNftMarketMakingPct: ${fmtNum(sfc.nft_market_making_pct) ?? 3},`,
    `    },`,
    `    graphql_endpoint: GRAPHQL_ENDPOINTS.${cluster},`,
    `  },`,
  ];

  return lines.join("\n");
}

function patchFrontendConfig() {
  if (!fs.existsSync(FRONTEND_CONFIG_PATH)) {
    console.error(`❌ Frontend config not found: ${FRONTEND_CONFIG_PATH}`);
    return;
  }
  const original = fs.readFileSync(FRONTEND_CONFIG_PATH, "utf-8");

  // Find the existing cluster block (prefer the cluster we're syncing; fall
  // back to any other cluster block already present so we can replace it).
  const preferredRegex = new RegExp(`${cluster}:\\s*\\{`);
  const fallbackRegex = /(devnet|mainnet|testnet):\s*\{/;
  let match = preferredRegex.exec(original);
  if (!match) match = fallbackRegex.exec(original);
  if (!match) {
    console.error(
      `❌ Could not find a cluster block ('${cluster}: {' or any devnet/mainnet/testnet block) in hooks/config.ts`,
    );
    return;
  }

  const startIdx = match.index;
  let braceCount = 0;
  let endIdx = -1;
  let inString = false;
  let stringChar = null;
  let escape = false;

  for (let i = startIdx; i < original.length; i++) {
    const ch = original[i];
    if (escape) {
      escape = false;
      continue;
    }
    if (ch === "\\") {
      escape = true;
      continue;
    }
    if (inString) {
      if (ch === stringChar) inString = false;
      continue;
    }
    if (ch === '"' || ch === "'" || ch === "`") {
      inString = true;
      stringChar = ch;
      continue;
    }
    if (ch === "{") braceCount++;
    if (ch === "}") {
      braceCount--;
      if (braceCount === 0) {
        endIdx = i;
        break;
      }
    }
  }

  if (endIdx === -1) {
    console.error(`❌ Could not find closing brace for cluster block (${cluster})`);
    return;
  }

  // We want to replace from '<cluster>: {' through the closing '}' (and the
  // trailing comma that separates it from the next CONFIGURATION entry).
  const before = original.slice(0, startIdx);

  // Skip the closing '}' and any following comma / whitespace so we don't
  // end up with double commas.
  let afterIdx = endIdx + 1;
  while (afterIdx < original.length && /[\s,]/.test(original[afterIdx])) {
    afterIdx++;
  }
  const after = original.slice(afterIdx);

  const newBlock = generateFrontendDevnetBlock();
  const marketProgramId = w?.programs?.market;
  let patched = before + newBlock + after;
  if (marketProgramId) {
    patched = patched.replace(
      /const DEVNET_DEGENBTC_MARKET_PROGRAM_ID = ".*?";/,
      `const DEVNET_DEGENBTC_MARKET_PROGRAM_ID = ${JSON.stringify(marketProgramId)};`,
    );
  }

  if (DRY_RUN) {
    console.log(
      `[DRY] Would patch ${path.relative(process.cwd(), FRONTEND_CONFIG_PATH)}`,
    );
    return;
  }

  fs.writeFileSync(FRONTEND_CONFIG_PATH, patched);
  console.log(`✅ Patched frontend hooks/config.ts ${cluster} block`);
}

// ═════════════════════════════════════════════════════════════════════════════
// RUN
// ═════════════════════════════════════════════════════════════════════════════

console.log(
  DRY_RUN ? "🔍 DRY RUN — no files will be modified\n" : "🚀 LIVE RUN\n",
);

copyIdls();
writeBackendDeployment();
patchFrontendConfig();

console.log("\n🎉 Sync complete.");
if (!DRY_RUN) {
  console.log("   Next steps:");
  console.log("   1. Review changes in MineBtcBackend/deployment.json");
  console.log("   2. Review changes in mdogeWifBtcFE/hooks/config.ts");
  console.log("   3. Commit + push both repos");
}
