[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
moon_base = "AKDm1gXxpnJE23aYTtmNE8E9CagM7gkvjKGegDZ9qTPD"
moon_economy = "CG6btG2MbTDXR2Ws6Kqn24HG6VqWWFJBrfxAK7NJVyNA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/Desktop/Solana/dogeTech/wallet-keypair.json"


[programs.localnet]
moon_base = "5Tn8VwVzcWK9BTSxJwrxqdFkL2oFEBQh1CVaetUYEdCw"
moon_economy = "9bB67dKDK2uSyhKeCkJmTuXsgUJkDpwBSF5EmgegRgVp"
